# Generated by Django 3.2.5 on 2021-07-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210729_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(related_name='article', through='articles.TagLink', to='articles.Tag'),
        ),
    ]
